Chocolatey distribution for Windows
Merrit/nyrna pull request #19
Opened 2020-10-12 00:05 UTC by Starz0r

I'm currently the package maintainer for the Chocolatey distribution on Windows. Saw one of the development goals was that, so I thought I add it to the README and knock it out of the goals for you.

2020-10-12 14:28 UTC, Merrit commented on README.md
> +[![latest packaged version(s)](https://repology.org/badge/latest-versions/nyrna.svg)](https://repology.org/project/nyrna/versions)
I think it looks better without these two, the verticle one under `# Installing` looks better too.
```suggestion
```

2020-10-12 14:29 UTC, Merrit commented on README.md
> +[![Packaging status](https://repology.org/badge/vertical-allrepos/nyrna.svg)](https://repology.org/project/nyrna/versions)
:+1:

2020-10-12 14:30 UTC, Merrit commented on README.md
> +Available in the [Chocolatey Community Packages repository](https://chocolatey.org/packages/nyrna)
Just needs a period to fit with the rest of the styling

```suggestion
Available in the [Chocolatey Community Packages repository.](https://chocolatey.org/packages/nyrna)
```

2020-10-12 14:30 UTC, Merrit commented on README.md
> +-   ~~Chocolatey distribution for Windows~~
```suggestion
- ~~Chocolatey distribution for Windows~~ ✅
```

2020-10-12 14:32 UTC, Merrit requested changes
This is great! Never even occurred to me someone might have done this.

Please check over my suggestions :smiley:

2020-10-12 22:22 UTC, Starz0r reviewed
Done!

2020-10-13 13:36 UTC, Merrit approved these changes
Very nice, thank you! :heart:

2020-10-13 13:37 UTC, merged